sudo: false
language: node_js
node_js:
  - 10
cache: npm
branches:
  only:
    - master
before_install:
    - rm -rvf public && mkdir public
    - git config --global user.name "johnsonlee"
    - git config --global user.email "g.johnsonlee@gmail.com"
script:
  - hexo generate
deploy:
  provider: script
  skip_cleanup: true
  script: bash .scripts/deploy.sh
  on:
      branch: master
