name: Deploy blog to GitHub page

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '12.4.0'

      - name: Install dependencies
        run: |
          npm install

      - name: Build
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: |
            rm -rvf public && mkdir public
            npm run build

      - name: Deploy
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: |
            cd public
            echo "johnsonlee.io" > CNAME
            git init
            git config user.name "johnsonlee"
            git config user.email "g.johnsonlee@gmail.com"
            git remote add origin https://johnsonlee:${GH_DEPLOY_TOKEN}@github.com/johnsonlee/johnsonlee.github.io.git
            git add .
            git commit -m "Deployed by GitHub actions" -a
            git push -u origin HEAD:master --force
        env:
          GH_DEPLOY_TOKEN: ${{ secrets.GH_DEPLOY_TOKEN }}
