name: Deploy blog to GitHub page

on:
  push:
    branches: [ master ]

  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: |
          npm install
      - name: Build
        run: |
          rm -rvf public && mkdir public
          npm run build
      - name: Deploy to johnsonlee.io
        working-directory: ./public
        run: |
          echo "johnsonlee.io" > CNAME
          rm -rf .git
          git init
          git config user.name "johnsonlee"
          git config user.email "g.johnsonlee@gmail.com"
          git remote add origin https://johnsonlee:${GH_DEPLOY_TOKEN}@github.com/johnsonlee/johnsonlee.github.io.git
          git add .
          git commit -m "Deployed by GitHub actions at $(date '+%F %T %:z')" -a
          git push -u origin HEAD:master --force
          git push -u origin HEAD:gh-pages --force
        env:
          GH_DEPLOY_TOKEN: ${{ secrets.GH_DEPLOY_TOKEN }}
      - name: Deploy to blog.johnsonlee.io
        working-directory: ./public
        run: |
          echo "blog.johnsonlee.io" > CNAME
          rm -rf .git
          git init
          git config user.name "johnsonlee"
          git config user.email "g.johnsonlee@gmail.com"
          git remote add origin https://johnsonlee:${GH_DEPLOY_TOKEN}@github.com/johnsonlee/blog.git
          git add .
          git commit -m "Deployed by GitHub actions at $(date '+%F %T %:z')" -a
          git push -u origin HEAD:gh-pages --force
        env:
          GH_DEPLOY_TOKEN: ${{ secrets.GH_DEPLOY_TOKEN }}
      - name: Upload error logs
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: logs
          path: ~/.npm/_logs/*.log

